[supabase]
url = "https://focduqznrmhjfixlfbau.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvY2R1cXpucm1oamZpeGxmYmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4OTQyMjAsImV4cCI6MjA3OTQ3MDIyMH0.dnj3fFo6BvX5zTpXSqmVdFCXzZPLJFO6ByJcjPHn6qo"
